version: "3.7"
services:
    nginx-polimundo:
        build:
            context: .
            dockerfile: nginx.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: nginx-polimundo
        ports: 
            - 80:80  
        networks: 
            polimundo_network:
                aliases: 
                    - nginx-polimundo 
        depends_on:
            mysql-polimundo:
                condition: service_healthy           
    laravel-polimundo:
        image: laravel/polimundo
        build:
            context: .
            dockerfile: polimundo.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: ${CUSTOMUID}
                CUSTOMGID: ${CUSTOMGID}    
        depends_on:
            mysql-polimundo:
                condition: service_healthy
        container_name: laravel-polimundo
        volumes:
            - ~/.ssh/:/root/.ssh/
        environment:
            - AMBIENTE=DESARROLLO  
            - APACHE_DOCUMENT_ROOT=/var/www/public 
        networks: 
            polimundo_network:
                aliases: 
                    - laravel-polimundo    
        tty: true
    mysql-polimundo:
        build:
            context: .
            dockerfile: mysql.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: mysql-polimundo
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports: 
            - 3306:3306  
        networks: 
            polimundo_network:
                aliases: 
                    - mysql-polimundo
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
            interval: 1m
            timeout: 10s
            retries: 5
networks: 
    polimundo_network:
        name: polimundo_net
        driver: bridge
        ipam:
            driver: default 
