version: "3.7"
services:
    nginx-polimundo:
        build:
            context: .
            dockerfile: nginx.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: nginx-polimundo
        ports: 
            - 80:80
        depends_on:
            - mysql-polimundo
        networks: 
            raul_network:
                aliases: 
                    - nginx-polimundo
    mysql-polimundo:
        build:
            context: .
            dockerfile: mysql.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: mysql-polimundo
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports: 
            - 3306:3306  
        networks: 
            raul_network:
                aliases: 
                    - mysql-polimundo   
    polimundo-prod:
        depends_on:
            - mysql-polimundo
        build:
            context: .
            dockerfile: polimundo.prod.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: polimundo-prod
        volumes:
            - ~/.ssh/:/root/.ssh/
        environment:
            - AMBIENTE=DESARROLLO  
            - APACHE_DOCUMENT_ROOT=/var/www/public
        networks: 
            raul_network:
                aliases: 
                    - polimundo-prod    
        tty: true
networks: 
    raul_network:
        name: raul_net
        driver: bridge
        ipam:
            driver: default 
