version: "3.7"
services:
    nginx-polimundo:
        build:
            context: .
            dockerfile: nginx.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: nginx-polimundo
        depends_on:
            - polimundo-prod
        ports: 
            - 80:80
            - 443:443    
        networks: 
            raul_network:
                aliases: 
                    - nginx-polimundo   
    polimundo-prod:
        image: polimundo/prod
        build:
            context: .
            dockerfile: polimundo.dev.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: ${CUSTOMUID}
                CUSTOMGID: ${CUSTOMGID}
        container_name: polimundo-prod
        volumes:
            - ~/.ssh/:/root/.ssh/
        environment:
            - AMBIENTE=DESARROLLO  
            - APACHE_DOCUMENT_ROOT=/var/www/public 
        networks: 
            raul_network:
                aliases: 
                    - polimundo-prod    
        tty: true
networks: 
    raul_network:
        name: raul_net
        driver: bridge
        ipam:
            driver: default 
